### ISSUE TITLE
Error: ENOENT: no such file or directory, open 'C:\Users\farih\golangg\ebook-bot/src/queries/SearchQuery.graphq

### ISSUE THREAD

**Issue by jakiepari** [luisbrandino/brainly-client#2]
How to fix this? i got this error Error: ENOENT: no such file or directory, open 'C:\Users\farih\golangg\ebook-bot/src/queries/SearchQuery.graphq

**Comment by luisbrandino** [comment]
Error fixed. It was an error in the path of file, please update the package. Thank you for opening this issue!
